blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/yourusername/youropensourcerepo/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://yourusername.github.io/youropensourcerepo/docs
    about: Check our documentation for answers to common questions.